name=HANUMAN_32_mini
version=0.1.1
author=hii-nice-2-meet-u <0x0.whitecat@gmail.com>
maintainer=hii-nice-2-meet-u <0x0.whitecat@gmail.com>
sentence=Arduino Library for HANUMAN-32 mini
paragraph=This library easy to read input and control output on Hanuman-32 mini Board. 
category=Device Control
url=https://github.com/hii-nice-2-meet-u/HANUMAN_32_mini
architectures=esp32
